import React, { useState } from 'react';
import { useData } from '../context/DataContext';
import { useAuth } from '../context/AuthContext';
import { ConfidenceBadge } from '../components/StatusBadge';
import {
  FileText,
  Sparkles,
  Bookmark,
  ThumbsUp,
  ThumbsDown,
  Activity,
  Sliders,
  CheckCircle2,
  TrendingUp,
  Clock,
  ShieldCheck
} from 'lucide-react';

export const GroundedSummariesPage = () => {
  const { cases, systemSettings, updateSettings } = useData();
  const { currentUser, hasPermission } = useAuth();

  const [threshold, setThreshold] = useState(systemSettings.aiConfidenceThreshold);
  const [feedbackState, setFeedbackState] = useState({}); // { [caseId]: 'up' | 'down' }
  const [feedbackComment, setFeedbackComment] = useState({});

  const handleSliderChange = (e) => {
    const val = Number(e.target.value);
    setThreshold(val);
    if (hasPermission('canManageSettings')) {
      updateSettings({ aiConfidenceThreshold: val }, currentUser);
    }
  };

  const handleFeedback = (caseId, type) => {
    setFeedbackState((prev) => ({ ...prev, [caseId]: type }));
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-900/60 p-6 rounded-2xl border border-slate-800 backdrop-blur-md">
        <div>
          <div className="flex items-center gap-2 text-cyan-400 font-semibold text-xs mb-1">
            <Sparkles className="w-4 h-4" /> AI Grounded Summaries & Citation Hub
          </div>
          <h1 className="text-xl font-bold text-slate-100">Traceable AI Decision Notes & Page Citations</h1>
          <p className="text-xs text-slate-400 mt-1">
            Every summary generated by Gemini 2.5 Flash is strictly grounded with source page and line citations. Configurable human-in-the-loop threshold routing.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <span className="bg-cyan-500/10 border border-cyan-500/30 text-cyan-300 text-xs font-semibold px-3 py-1.5 rounded-xl flex items-center gap-1.5 font-mono">
            <Bookmark className="w-4 h-4 text-cyan-400" /> Page & Section Grounded
          </span>
        </div>
      </div>

      {/* Model Performance & Drift Dashboard */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="glass-card p-4 rounded-xl space-y-1">
          <span className="text-xs text-slate-400">Extraction Accuracy</span>
          <p className="text-2xl font-extrabold text-emerald-400">98.4%</p>
          <span className="text-[10px] text-emerald-400 flex items-center gap-1">
            <TrendingUp className="w-3 h-3" /> +1.2% this month
          </span>
        </div>

        <div className="glass-card p-4 rounded-xl space-y-1">
          <span className="text-xs text-slate-400">Model Inference Latency</span>
          <p className="text-2xl font-extrabold text-cyan-300 font-mono">420 ms</p>
          <span className="text-[10px] text-slate-400 flex items-center gap-1">
            <Clock className="w-3 h-3 text-cyan-400" /> Gemini API Latency
          </span>
        </div>

        <div className="glass-card p-4 rounded-xl space-y-1">
          <span className="text-xs text-slate-400">Drift Indicator</span>
          <p className="text-2xl font-extrabold text-slate-200">0.02</p>
          <span className="text-[10px] text-emerald-400">Stable Baseline</span>
        </div>

        <div className="glass-card p-4 rounded-xl space-y-1">
          <span className="text-xs text-slate-400">Reviewer Override Rate</span>
          <p className="text-2xl font-extrabold text-purple-400">3.8%</p>
          <span className="text-[10px] text-purple-400">High Human Alignment</span>
        </div>
      </div>

      {/* Threshold Configuration Controls */}
      <div className="glass-panel p-6 rounded-2xl border border-slate-800 space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <Sliders className="w-4 h-4 text-cyan-400" />
            <h2 className="text-sm font-bold text-slate-100">Auto-Routing Confidence Threshold Configuration</h2>
          </div>
          <span className="text-xs text-cyan-400 font-bold font-mono bg-cyan-500/10 px-3 py-1 rounded-lg border border-cyan-500/30">
            Routing Threshold: {threshold}%
          </span>
        </div>

        <div className="space-y-2">
          <div className="flex justify-between text-xs text-slate-400 font-mono">
            <span>Aggressive (70%)</span>
            <span>Balanced (85% Default)</span>
            <span>Strict Human Review (95%)</span>
          </div>
          <input
            type="range"
            min="60"
            max="95"
            step="1"
            value={threshold}
            onChange={handleSliderChange}
            disabled={!hasPermission('canManageSettings')}
            className="w-full h-2 bg-slate-950 rounded-lg appearance-none cursor-pointer accent-cyan-400"
          />
          <p className="text-xs text-slate-400">
            Documents with overall AI confidence below <strong className="text-cyan-300">{threshold}%</strong> are automatically routed to the Reviewer exception queue.
          </p>
        </div>
      </div>

      {/* Grounded Summaries Cards */}
      <div className="space-y-4">
        <h2 className="text-sm font-bold text-slate-100 flex items-center gap-2">
          <FileText className="w-4 h-4 text-cyan-400" /> Case Grounded Notes & Evidence Lineage
        </h2>

        {cases.map((c) => (
          <div key={c.id} className="glass-panel p-5 rounded-2xl border border-slate-800 space-y-3">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800 pb-2">
              <div className="flex items-center gap-2">
                <span className="font-bold text-sm text-slate-100">{c.title}</span>
                <span className="text-xs text-slate-500 font-mono">({c.id})</span>
              </div>
              <ConfidenceBadge score={c.confidenceScore} />
            </div>

            <div className="p-4 bg-slate-950/80 rounded-xl border border-slate-800 text-xs text-slate-300 space-y-2 font-sans leading-relaxed">
              <p className="font-medium text-slate-200">{c.summaryCitation}</p>
            </div>

            {/* Citation Badges */}
            <div className="flex flex-wrap items-center gap-2 pt-1">
              <span className="text-[11px] text-slate-400 font-semibold">Citations:</span>
              <span className="text-[10px] font-mono bg-cyan-500/10 text-cyan-300 border border-cyan-500/30 px-2 py-0.5 rounded">
                [Pg.1 §1 Header Log]
              </span>
              <span className="text-[10px] font-mono bg-cyan-500/10 text-cyan-300 border border-cyan-500/30 px-2 py-0.5 rounded">
                [Pg.1 §2 Quality Lab Reading]
              </span>
              <span className="text-[10px] font-mono bg-slate-800 text-slate-400 px-2 py-0.5 rounded">
                Model: {systemSettings.modelName}
              </span>
            </div>

            {/* Feedback Collector */}
            <div className="flex items-center justify-between pt-2 border-t border-slate-800/80 text-xs">
              <span className="text-slate-400">Was this grounded AI summary accurate & helpful?</span>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleFeedback(c.id, 'up')}
                  className={`p-1.5 rounded-lg border transition-colors flex items-center gap-1 ${
                    feedbackState[c.id] === 'up'
                      ? 'bg-emerald-500/20 text-emerald-400 border-emerald-500/40'
                      : 'bg-slate-950 text-slate-400 border-slate-800 hover:text-white'
                  }`}
                >
                  <ThumbsUp className="w-3.5 h-3.5" /> Accurate
                </button>
                <button
                  onClick={() => handleFeedback(c.id, 'down')}
                  className={`p-1.5 rounded-lg border transition-colors flex items-center gap-1 ${
                    feedbackState[c.id] === 'down'
                      ? 'bg-rose-500/20 text-rose-400 border-rose-500/40'
                      : 'bg-slate-950 text-slate-400 border-slate-800 hover:text-white'
                  }`}
                >
                  <ThumbsDown className="w-3.5 h-3.5" /> Inaccurate
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
